### ISSUE TITLE
Travis build not working with Papermill

### ISSUE THREAD

**Issue by MattForshaw** [MattForshaw/zurich-bikes#1]
Hi @betatim, 

I've followed the instructions from https://github.com/betatim/reproducible-science-tools/blob/master/tools.md to no avail. Do you have any suggestions?

You can see the details of a failed build at: https://travis-ci.org/MattForshaw/zurich-bikes/builds/427075841

Despite adding a pip install for papermill, it doesn't seem to be happy finding it.

`docker.errors.APIError: 400 Client Error: Bad Request ("oci runtime error: container_linux.go:265: starting container process caused "exec: \"papermill\": executable file not found in $PATH"
`

Any help much appreciated!

Best wishes,
Matt

**Comment by betatim** [comment]
The problem is that papermill needs to be installed inside the container that `repo2docker` builds. So you need to add it to your `environment.yml`, not install it on the host machine (via `.travis.yml`).

**Comment by MattForshaw** [comment]
Thank you very much, Tim! This is working perfectly now.

I'll raise a quick PR to add some clarification.

Best wishes,
Matt
